import { User, PriceRegistration, Mission, PriceAlert, LocalOffer, NeighborhoodRank, Transaction, Notification, Product, Cart } from './types';

// ─── Current Logged User ───────────────────────────────────────────────────
export const CURRENT_USER: User = {
  id: 'user-001',
  name: 'João Silva',
  email: 'joao@email.com',
  phone: '27999999999',
  avatar: 'JS',
  level: 'guardiao',
  points: 1240,
  walletBalance: 24.75,
  referralCode: 'JOAO2024',
  referredBy: null,
  referrals: ['user-002', 'user-003', 'user-004', 'user-005', 'user-006'],
  neighborhood: 'Jardim Camburi',
  city: 'Vitória',
  state: 'ES',
  registeredAt: '2024-01-15',
  totalRegistrations: 248,
  confirmedRegistrations: 231,
  networkSize: 34,
};

// ─── Network Users ─────────────────────────────────────────────────────────
export const NETWORK_USERS: User[] = [
  {
    id: 'user-002', name: 'Maria Santos', email: 'maria@email.com', phone: '', avatar: 'MS',
    level: 'explorador', points: 320, walletBalance: 4.50, referralCode: 'MARIA2024',
    referredBy: 'user-001', referrals: ['user-007', 'user-008'],
    neighborhood: 'Jardim Camburi', city: 'Vitória', state: 'ES',
    registeredAt: '2024-02-01', totalRegistrations: 64, confirmedRegistrations: 58, networkSize: 2,
  },
  {
    id: 'user-003', name: 'Carlos Oliveira', email: 'carlos@email.com', phone: '', avatar: 'CO',
    level: 'explorador', points: 180, walletBalance: 2.80, referralCode: 'CARL2024',
    referredBy: 'user-001', referrals: ['user-009'],
    neighborhood: 'Bento Ferreira', city: 'Vitória', state: 'ES',
    registeredAt: '2024-02-10', totalRegistrations: 36, confirmedRegistrations: 32, networkSize: 1,
  },
  {
    id: 'user-004', name: 'Ana Costa', email: 'ana@email.com', phone: '', avatar: 'AC',
    level: 'explorador', points: 240, walletBalance: 3.20, referralCode: 'ANA2024',
    referredBy: 'user-001', referrals: ['user-010', 'user-011', 'user-012'],
    neighborhood: 'Jardim da Penha', city: 'Vitória', state: 'ES',
    registeredAt: '2024-02-15', totalRegistrations: 48, confirmedRegistrations: 44, networkSize: 3,
  },
  {
    id: 'user-005', name: 'Pedro Lima', email: 'pedro@email.com', phone: '', avatar: 'PL',
    level: 'explorador', points: 160, walletBalance: 2.40, referralCode: 'PEDR2024',
    referredBy: 'user-001', referrals: [],
    neighborhood: 'Goiabeiras', city: 'Vitória', state: 'ES',
    registeredAt: '2024-03-01', totalRegistrations: 32, confirmedRegistrations: 28, networkSize: 0,
  },
  {
    id: 'user-006', name: 'Fernanda Rocha', email: 'fernanda@email.com', phone: '', avatar: 'FR',
    level: 'explorador', points: 210, walletBalance: 3.10, referralCode: 'FERN2024',
    referredBy: 'user-001', referrals: ['user-013', 'user-014'],
    neighborhood: 'Maria Ortiz', city: 'Vila Velha', state: 'ES',
    registeredAt: '2024-03-05', totalRegistrations: 42, confirmedRegistrations: 38, networkSize: 2,
  },
];

// ─── Price Registrations ───────────────────────────────────────────────────
export const PRICE_REGISTRATIONS: PriceRegistration[] = [
  {
    id: 'reg-001', userId: 'user-001', userName: 'João Silva',
    productName: 'Arroz Agulhinha 5kg', productCategory: 'Mercearia', productBrand: 'Camil',
    price: 28.90, unit: '5kg', storeName: 'Supermercado Extra', storeAddress: 'Av. Fernando Ferrari, 1000',
    neighborhood: 'Jardim Camburi', city: 'Vitória', state: 'ES', lat: -20.2810, lng: -40.2958,
    confirmedBy: ['user-002', 'user-003', 'user-004'], flaggedBy: [],
    status: 'confirmed', registeredAt: '2024-03-20T10:30:00', missionId: undefined,
  },
  {
    id: 'reg-002', userId: 'user-001', userName: 'João Silva',
    productName: 'Ovos Brancos C30', productCategory: 'Hortifrúti', productBrand: 'Mantiqueira',
    price: 18.50, unit: 'dz', storeName: 'Atacadão', storeAddress: 'Av. Central, 500',
    neighborhood: 'Jardim Camburi', city: 'Vitória', state: 'ES', lat: -20.2750, lng: -40.2900,
    confirmedBy: ['user-004', 'user-005'], flaggedBy: [],
    status: 'confirmed', registeredAt: '2024-03-21T14:00:00',
  },
  {
    id: 'reg-003', userId: 'user-002', userName: 'Maria Santos',
    productName: 'Leite Integral 1L', productCategory: 'Laticínios', productBrand: 'Italac',
    price: 4.89, unit: '1L', storeName: 'Mercadinho do Bairro', storeAddress: 'Rua das Flores, 45',
    neighborhood: 'Jardim Camburi', city: 'Vitória', state: 'ES', lat: -20.2780, lng: -40.2940,
    confirmedBy: ['user-001', 'user-003'], flaggedBy: [],
    status: 'confirmed', registeredAt: '2024-03-21T09:00:00',
  },
  {
    id: 'reg-004', userId: 'user-003', userName: 'Carlos Oliveira',
    productName: 'Óleo de Soja 900ml', productCategory: 'Mercearia', productBrand: 'Liza',
    price: 7.99, unit: '900ml', storeName: 'Rede Perim', storeAddress: 'Av. Marechal Campos, 200',
    neighborhood: 'Bento Ferreira', city: 'Vitória', state: 'ES', lat: -20.3100, lng: -40.3200,
    confirmedBy: ['user-001'], flaggedBy: [],
    status: 'confirmed', registeredAt: '2024-03-22T11:30:00',
  },
  {
    id: 'reg-005', userId: 'user-001', userName: 'João Silva',
    productName: 'Feijão Carioca 1kg', productCategory: 'Mercearia', productBrand: 'Kicaldo',
    price: 8.49, unit: '1kg', storeName: 'Supermercado Extra', storeAddress: 'Av. Fernando Ferrari, 1000',
    neighborhood: 'Jardim Camburi', city: 'Vitória', state: 'ES', lat: -20.2810, lng: -40.2958,
    confirmedBy: ['user-002', 'user-005', 'user-006'], flaggedBy: [],
    status: 'confirmed', registeredAt: '2024-03-22T16:00:00', missionId: 'mission-001',
  },
];

// ─── Products ──────────────────────────────────────────────────────────────
export const PRODUCTS: Product[] = [
  { id: 'p-001', name: 'Arroz Agulhinha 5kg', category: 'Mercearia', brand: 'Camil', unit: '5kg', avgPrice: 27.50, minPrice: 24.90, maxPrice: 31.90, registrationCount: 142 },
  { id: 'p-002', name: 'Feijão Carioca 1kg', category: 'Mercearia', brand: 'Kicaldo', unit: '1kg', avgPrice: 8.20, minPrice: 6.99, maxPrice: 10.50, registrationCount: 98 },
  { id: 'p-003', name: 'Óleo de Soja 900ml', category: 'Mercearia', brand: 'Liza', unit: '900ml', avgPrice: 7.80, minPrice: 6.49, maxPrice: 9.99, registrationCount: 87 },
  { id: 'p-004', name: 'Leite Integral 1L', category: 'Laticínios', brand: 'Italac', unit: '1L', avgPrice: 4.75, minPrice: 3.99, maxPrice: 5.99, registrationCount: 203 },
  { id: 'p-005', name: 'Ovos Brancos C30', category: 'Hortifrúti', brand: 'Mantiqueira', unit: 'cx30', avgPrice: 16.90, minPrice: 13.90, maxPrice: 21.90, registrationCount: 156 },
  { id: 'p-006', name: 'Frango Inteiro kg', category: 'Carnes & Aves', brand: 'Seara', unit: 'kg', avgPrice: 11.90, minPrice: 9.99, maxPrice: 14.90, registrationCount: 119 },
  { id: 'p-007', name: 'Açúcar Cristal 1kg', category: 'Mercearia', brand: 'Guarani', unit: '1kg', avgPrice: 4.50, minPrice: 3.79, maxPrice: 5.99, registrationCount: 76 },
  { id: 'p-008', name: 'Macarrão Espaguete 500g', category: 'Mercearia', brand: 'Barilla', unit: '500g', avgPrice: 5.90, minPrice: 4.49, maxPrice: 7.99, registrationCount: 64 },
];

// ─── Missions ─────────────────────────────────────────────────────────────
export const MISSIONS: Mission[] = [
  {
    id: 'mission-001',
    brandId: 'brand-001',
    brandName: 'Kicaldo',
    brandLogo: 'K',
    title: 'Mapeamento de Feijão Carioca no ES',
    description: 'Registre o preço do Feijão Carioca Kicaldo 1kg em mercados da Grande Vitória. Quanto mais mercados, mais você ganha!',
    type: 'price_check',
    productName: 'Feijão Carioca 1kg',
    productBrand: 'Kicaldo',
    targetCity: 'Vitória',
    rewardPerUser: 2.00,
    brandCost: 3.50,
    totalSlots: 500,
    filledSlots: 287,
    status: 'active',
    expiresAt: '2024-04-15',
    createdAt: '2024-03-15',
    participants: ['user-001', 'user-002', 'user-004'],
    completedBy: ['user-001'],
    bonusForReferrals: 1.00,
  },
  {
    id: 'mission-002',
    brandId: 'brand-002',
    brandName: 'Italac',
    brandLogo: 'I',
    title: 'Auditoria de Leite Italac',
    description: 'Verifique presença e preço do Leite Integral Italac 1L em 3 supermercados diferentes. Ganhe bônus por trazer amigos!',
    type: 'shelf_audit',
    productName: 'Leite Integral 1L',
    productBrand: 'Italac',
    targetCity: 'Vila Velha',
    rewardPerUser: 3.00,
    brandCost: 5.25,
    totalSlots: 300,
    filledSlots: 142,
    status: 'active',
    expiresAt: '2024-04-10',
    createdAt: '2024-03-10',
    participants: ['user-003', 'user-005'],
    completedBy: [],
    bonusForReferrals: 1.50,
  },
  {
    id: 'mission-003',
    brandId: 'brand-003',
    brandName: 'Seara',
    brandLogo: 'S',
    title: 'Comparativo de Frango - ES',
    description: 'Compare o preço do Frango Inteiro Seara com concorrentes (Sadia, Perdigão) no seu mercado. Dados valiosos para nós!',
    type: 'competitor_compare',
    productName: 'Frango Inteiro kg',
    productBrand: 'Seara',
    targetCity: 'Vitória',
    rewardPerUser: 4.00,
    brandCost: 7.00,
    totalSlots: 200,
    filledSlots: 89,
    status: 'active',
    expiresAt: '2024-04-20',
    createdAt: '2024-03-18',
    participants: [],
    completedBy: [],
    bonusForReferrals: 2.00,
  },
  {
    id: 'mission-004',
    brandId: 'brand-004',
    brandName: 'Camil',
    brandLogo: 'C',
    title: '🏆 Caça ao Tesouro — Arroz Camil mais barato',
    description: 'Encontre o mercado com o menor preço do Arroz Camil 5kg na sua cidade. Quem trouxer amigos que também encontrem, ganha bônus coletivo!',
    type: 'treasure_hunt',
    productName: 'Arroz Agulhinha 5kg',
    productBrand: 'Camil',
    targetCity: 'Vitória',
    rewardPerUser: 5.00,
    brandCost: 8.75,
    totalSlots: 100,
    filledSlots: 34,
    status: 'active',
    expiresAt: '2024-03-30',
    createdAt: '2024-03-20',
    participants: ['user-001'],
    completedBy: [],
    bonusForReferrals: 3.00,
  },
];

// ─── Price Alerts ──────────────────────────────────────────────────────────
export const PRICE_ALERTS: PriceAlert[] = [
  {
    id: 'alert-001',
    productName: 'Ovos Brancos C30',
    registrationId: 'reg-002',
    price: 18.50,
    avgPrice: 16.90,
    percentAbove: 9.5,
    storeName: 'Atacadão',
    neighborhood: 'Jardim Camburi',
    city: 'Vitória',
    reportedBy: 'João Silva',
    createdAt: '2024-03-21T14:00:00',
    shares: 47,
    confirmedCount: 12,
  },
  {
    id: 'alert-002',
    productName: 'Frango Inteiro kg',
    registrationId: 'reg-new',
    price: 18.90,
    avgPrice: 11.90,
    percentAbove: 58.8,
    storeName: 'Mini Mercado Expresso',
    neighborhood: 'Bento Ferreira',
    city: 'Vitória',
    reportedBy: 'Carlos Oliveira',
    createdAt: '2024-03-22T09:30:00',
    shares: 124,
    confirmedCount: 8,
  },
  {
    id: 'alert-003',
    productName: 'Leite Integral 1L',
    registrationId: 'reg-new2',
    price: 9.90,
    avgPrice: 4.75,
    percentAbove: 108.4,
    storeName: 'Conveniência do Aeroporto',
    neighborhood: 'Goiabeiras',
    city: 'Vitória',
    reportedBy: 'Ana Costa',
    createdAt: '2024-03-22T15:00:00',
    shares: 289,
    confirmedCount: 23,
  },
];

// ─── Local Offers (Marketplace) ────────────────────────────────────────────
export const LOCAL_OFFERS: LocalOffer[] = [
  {
    id: 'offer-001',
    storeId: 'store-001',
    storeName: 'Padaria Pão Quente',
    storeCategory: 'Padaria',
    storeAddress: 'Rua do Pão, 123',
    neighborhood: 'Jardim Camburi',
    city: 'Vitória',
    productName: 'Pão Francês',
    originalPrice: 0.50,
    offerPrice: 0.35,
    discountPercent: 30,
    description: 'Pão fresquinho saindo do forno! Promoção válida das 17h às 19h.',
    validUntil: '2024-03-31',
    views: 342,
    checkIns: 87,
    costPerClick: 0.30,
    costPerCheckIn: 1.20,
    active: true,
    createdAt: '2024-03-20',
    distance: 0.3,
  },
  {
    id: 'offer-002',
    storeId: 'store-002',
    storeName: 'Açougue do Tonho',
    storeCategory: 'Carnes',
    storeAddress: 'Av. Principal, 456',
    neighborhood: 'Jardim Camburi',
    city: 'Vitória',
    productName: 'Picanha Angus kg',
    originalPrice: 89.90,
    offerPrice: 69.90,
    discountPercent: 22,
    description: 'Picanha Angus selecionada. Estoque limitado!',
    validUntil: '2024-03-25',
    views: 891,
    checkIns: 156,
    costPerClick: 0.30,
    costPerCheckIn: 1.50,
    active: true,
    createdAt: '2024-03-21',
    distance: 0.8,
  },
  {
    id: 'offer-003',
    storeId: 'store-003',
    storeName: 'Hortifrúti da Família',
    storeCategory: 'Hortifrúti',
    storeAddress: 'Rua Verde, 78',
    neighborhood: 'Jardim Camburi',
    city: 'Vitória',
    productName: 'Manga Palmer kg',
    originalPrice: 8.90,
    offerPrice: 4.99,
    discountPercent: 44,
    description: 'Manga madura e doce! Leve 2kg e ganhe desconto extra.',
    validUntil: '2024-03-24',
    views: 567,
    checkIns: 203,
    costPerClick: 0.25,
    costPerCheckIn: 1.00,
    active: true,
    createdAt: '2024-03-22',
    distance: 0.2,
  },
];

// ─── Neighborhood Ranking ──────────────────────────────────────────────────
export const NEIGHBORHOOD_RANKING: NeighborhoodRank[] = [
  { id: 'nb-001', name: 'Jardim Camburi', city: 'Vitória', state: 'ES', totalRegistrations: 1248, totalUsers: 87, totalSavings: 3420.50, topContributor: 'João Silva', weeklyGrowth: 12, rank: 1 },
  { id: 'nb-002', name: 'Jardim da Penha', city: 'Vitória', state: 'ES', totalRegistrations: 987, totalUsers: 64, totalSavings: 2890.20, topContributor: 'Ana Costa', weeklyGrowth: 8, rank: 2 },
  { id: 'nb-003', name: 'Praia do Canto', city: 'Vitória', state: 'ES', totalRegistrations: 843, totalUsers: 52, totalSavings: 2340.80, topContributor: 'Rafael Mendes', weeklyGrowth: 15, rank: 3 },
  { id: 'nb-004', name: 'Bento Ferreira', city: 'Vitória', state: 'ES', totalRegistrations: 756, totalUsers: 48, totalSavings: 2100.60, topContributor: 'Carlos Oliveira', weeklyGrowth: 5, rank: 4 },
  { id: 'nb-005', name: 'Mata da Praia', city: 'Vitória', state: 'ES', totalRegistrations: 698, totalUsers: 43, totalSavings: 1980.30, topContributor: 'Lucia Ferreira', weeklyGrowth: 20, rank: 5 },
  { id: 'nb-006', name: 'Goiabeiras', city: 'Vitória', state: 'ES', totalRegistrations: 645, totalUsers: 41, totalSavings: 1820.10, topContributor: 'Pedro Lima', weeklyGrowth: 3, rank: 6 },
  { id: 'nb-007', name: 'Maria Ortiz', city: 'Vila Velha', state: 'ES', totalRegistrations: 589, totalUsers: 38, totalSavings: 1650.70, topContributor: 'Fernanda Rocha', weeklyGrowth: 18, rank: 7 },
];

// ─── Transactions ──────────────────────────────────────────────────────────
export const TRANSACTIONS: Transaction[] = [
  { id: 'tx-001', userId: 'user-001', type: 'earn_registration', amount: 0.10, description: 'Registro confirmado: Arroz Agulhinha 5kg', reference: 'reg-001', createdAt: '2024-03-20T10:35:00' },
  { id: 'tx-002', userId: 'user-001', type: 'earn_network', amount: 0.06, description: 'Bônus de rede: Maria Santos (Leite Integral)', reference: 'reg-003', createdAt: '2024-03-21T09:05:00' },
  { id: 'tx-003', userId: 'user-001', type: 'earn_registration', amount: 0.10, description: 'Registro confirmado: Ovos Brancos C30', reference: 'reg-002', createdAt: '2024-03-21T14:05:00' },
  { id: 'tx-004', userId: 'user-001', type: 'earn_network', amount: 0.06, description: 'Bônus de rede: Carlos Oliveira (Óleo de Soja)', reference: 'reg-004', createdAt: '2024-03-22T11:35:00' },
  { id: 'tx-005', userId: 'user-001', type: 'earn_mission', amount: 2.00, description: 'Missão concluída: Mapeamento Feijão Kicaldo', reference: 'mission-001', createdAt: '2024-03-22T16:05:00' },
  { id: 'tx-006', userId: 'user-001', type: 'earn_bonus', amount: 5.00, description: 'Bônus de boas-vindas Zei', createdAt: '2024-01-15T08:00:00' },
  { id: 'tx-007', userId: 'user-001', type: 'withdraw', amount: -10.00, description: 'Saque via Pix — chave: joao@email.com', createdAt: '2024-03-10T12:00:00' },
  { id: 'tx-008', userId: 'user-001', type: 'earn_registration', amount: 0.10, description: 'Registro confirmado: Feijão Carioca 1kg', reference: 'reg-005', createdAt: '2024-03-22T16:10:00' },
];

// ─── Notifications ─────────────────────────────────────────────────────────
export const NOTIFICATIONS: Notification[] = [
  { id: 'notif-001', userId: 'user-001', type: 'reward', title: 'Registro confirmado! 🎉', message: 'Seu registro do Arroz Camil foi confirmado por 3 pessoas. +R$0,10 na carteira!', read: false, createdAt: '2024-03-20T11:00:00' },
  { id: 'notif-002', userId: 'user-001', type: 'mission', title: 'Nova missão disponível 🎯', message: 'Kicaldo lançou uma missão paga para sua cidade. Ganhe R$2,00 por registro!', read: false, createdAt: '2024-03-21T08:00:00' },
  { id: 'notif-003', userId: 'user-001', type: 'network', title: 'Nova pessoa na sua rede 👥', message: 'Fernanda Rocha entrou no Zei pelo seu convite!', read: false, createdAt: '2024-03-21T15:30:00' },
  { id: 'notif-004', userId: 'user-001', type: 'alert', title: 'Preço absurdo detectado! 🚨', message: 'Leite a R$9,90 em Goiabeiras? Confirma aí!', read: true, createdAt: '2024-03-22T15:05:00' },
  { id: 'notif-005', userId: 'user-001', type: 'level_up', title: 'Quase no próximo nível! ⬆️', message: 'Você está perto de se tornar Capitão de Região. Recrute mais 3 pessoas ativas!', read: true, createdAt: '2024-03-19T10:00:00' },
];

// ─── Cart (Cart Challenge) ─────────────────────────────────────────────────
export const SAMPLE_CART: Cart = {
  id: 'cart-001',
  userId: 'user-001',
  items: [
    { id: 'ci-001', productName: 'Arroz Agulhinha 5kg', quantity: 1, price: 28.90, storeName: 'Supermercado Extra' },
    { id: 'ci-002', productName: 'Feijão Carioca 1kg', quantity: 2, price: 8.49, storeName: 'Supermercado Extra' },
    { id: 'ci-003', productName: 'Óleo de Soja 900ml', quantity: 1, price: 7.99, storeName: 'Supermercado Extra' },
    { id: 'ci-004', productName: 'Leite Integral 1L', quantity: 4, price: 4.89, storeName: 'Supermercado Extra' },
    { id: 'ci-005', productName: 'Ovos Brancos C30', quantity: 1, price: 18.50, storeName: 'Supermercado Extra' },
  ],
  totalSpent: 94.34,
  neighborhood: 'Jardim Camburi',
  city: 'Vitória',
  createdAt: '2024-03-22T16:00:00',
  shared: false,
};
